parameters:
    app.path.article_images: /images/articles
    app.path.cat_images: /uploads/images/categories

vich_uploader:
    db_driver: orm
    mappings:
        article_images:
            uri_prefix:         '/images/articles'
            upload_destination: '%kernel.project_dir%/web/images/articles'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true