<?php

namespace ApiBundle\Repository;

/**
 * LogActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
